jwt:
  secret:
    key: ${JWT_SECRET_KEY:dGhpc2lzYXZlcnlzZWN1cmVrZXlmb3Jqd3R0b2tlbmVuY3J5cHRpb25wdXJwb3Nlc2FuZGl0c2hvdWxkYmVsb25nZW5vdWdo}
  expiration: ${JWT_EXPIRATION:86400000}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/stitch}
    username: ${DATABASE_USERNAME:stitch_user1}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
